In [2]:
import torch
import matplotlib.pyplot as plt

In [33]:
# create a small neural network with 1 hidden layer
class Net(torch.nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = torch.nn.Linear(3, 10)
        self.fc2 = torch.nn.Linear(10, 1)

    def forward(self, x):
        x = torch.tanh(self.fc1(x))
        x = self.fc2(x)

        return x

net = Net()

In [35]:
n_samples = 20
x_batch = torch.randn(n_samples, 3,requires_grad=True)
x1,x2,x3 = x_batch[:,0:1], x_batch[:,1:2], x_batch[:,2:3]
print(x1)
x_batch = torch.concat([x1,x2,x3],dim=1)
# x_batch.requires_grad = True

tensor([[ 0.4937],
        [-0.1096],
        [-0.2354],
        [-0.8136],
        [-1.2618],
        [ 0.5843],
        [ 0.7163],
        [ 1.6449],
        [-1.0383],
        [ 0.6091],
        [ 0.1979],
        [ 0.8264],
        [ 0.0019],
        [ 1.6107],
        [ 0.8073],
        [-1.1505],
        [ 1.0902],
        [ 0.3509],
        [ 0.7590],
        [-0.6202]], grad_fn=<SliceBackward0>)


In [36]:
# evaluate network
u_batch = net(x_batch)

In [44]:
# compute first and second derivative. All at once.
dudx = torch.autograd.grad(outputs = u_batch, inputs = x_batch, grad_outputs= torch.ones_like(u_batch), create_graph=True)[0]
corrected_dudx = torch.autograd.grad(outputs = u_batch, inputs = x1, grad_outputs= torch.ones_like(u_batch), create_graph=True)[0]
d2udx2 = torch.autograd.grad(outputs = dudx, inputs = x_batch, grad_outputs= torch.ones_like(dudx), create_graph=True)[0]
corrected_d2udx2 = torch.autograd.grad(outputs = dudx[:,0], inputs = x1, grad_outputs= torch.ones_like(dudx[:,0]), create_graph=True)[0]

In [45]:
dudx.shape

torch.Size([20, 3])

In [46]:
d2udx2.shape

torch.Size([20, 3])

In [47]:
corrected_d2udx2

tensor([[ 0.0323],
        [ 0.0337],
        [ 0.0151],
        [-0.0041],
        [-0.0387],
        [ 0.0184],
        [ 0.0285],
        [-0.0063],
        [ 0.0020],
        [-0.0105],
        [ 0.0288],
        [ 0.0365],
        [ 0.0091],
        [ 0.0248],
        [ 0.0287],
        [ 0.0194],
        [ 0.0264],
        [ 0.0220],
        [ 0.0322],
        [-0.0117]], grad_fn=<SliceBackward0>)

In [48]:
d2udx2

tensor([[-0.0116,  0.0038, -0.0665],
        [-0.0097,  0.0192, -0.0381],
        [ 0.0038,  0.0004, -0.0636],
        [-0.0046, -0.0329, -0.0894],
        [-0.0189, -0.1269, -0.0609],
        [-0.0111, -0.0182,  0.0007],
        [-0.0087, -0.0274, -0.0765],
        [ 0.0339,  0.0345,  0.0644],
        [-0.0437, -0.0304,  0.0389],
        [ 0.0205,  0.0010,  0.0269],
        [-0.0076, -0.0193, -0.0804],
        [ 0.0239,  0.0583,  0.0076],
        [ 0.0023, -0.0087, -0.0546],
        [-0.0005, -0.0100, -0.0185],
        [-0.0081,  0.0064, -0.0205],
        [-0.0193, -0.0185, -0.0115],
        [ 0.0340,  0.0770,  0.0295],
        [-0.0204, -0.0474, -0.0663],
        [-0.0138,  0.0058, -0.0631],
        [-0.0334, -0.1038, -0.0408]], grad_fn=<MmBackward0>)