In [18]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader, TensorDataset
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(2, 2)  # Input layer -> Hidden layer
        self.fc2 = nn.Linear(2, 1)  # Hidden layer -> Output layer

    def forward(self, x):
        x = torch.tanh(self.fc1(x))  # Activation function for the hidden layer
        x = torch.tanh(self.fc2(x))  # Activation function for the output layer
        return x


In [64]:
X1 = torch.tensor([[0.0],
                  [0.0],
                  [1.0],
                  [1.0]],requires_grad=True)
X2 = torch.tensor([[0.0],
                   [1.0],
                   [0.0],
                   [1.0]],requires_grad=True)

mod = SimpleNN()

In [77]:

# mod.forward(X)


# output = torch.concat([output,output],dim=1)
input = torch.concat([X1,X2],dim=1)
output = mod.forward(input)
f_prime = torch.autograd.grad(outputs =  output , inputs = input, grad_outputs = torch.ones_like(output), create_graph=True)[0]
uy = torch.autograd.grad(outputs =  output , inputs = X2, grad_outputs = torch.ones_like(output), create_graph=True)[0]
print(uy)

u_x = f_prime[:, 0]
u_y = f_prime[:, 1]
print(u_y)

y = torch.autograd.grad(outputs = uy, inputs = input, grad_outputs = torch.ones_like(uy), create_graph=True)[0]
print(y)

y = torch.autograd.grad(outputs = u_y, inputs = X2,  grad_outputs = torch.ones_like(u_y), create_graph=True)[0]
print(y)




tensor([[0.4401],
        [0.2172],
        [0.4374],
        [0.3551]], grad_fn=<SliceBackward0>)
tensor([0.4401, 0.2172, 0.4374, 0.3551], grad_fn=<SelectBackward0>)
tensor([[ 0.0740, -0.1237],
        [ 0.1297, -0.2192],
        [-0.0734,  0.1220],
        [ 0.1287, -0.2360]], grad_fn=<MmBackward0>)
tensor([[-0.1237],
        [-0.2192],
        [ 0.1220],
        [-0.2360]], grad_fn=<SliceBackward0>)


In [ ]:
partial_derivatives[el[i][2]] = torch.autograd.grad(outputs=partial_derivatives[el[0]], inputs= partial_derivatives[el[1]], grad_outputs=torch.ones_like(partial_derivatives[el[0]]), create_graph=True)[0]

In [1]:

't' in [('u','t')]

False